# Chainlink CRE - YieldProp Project Configuration
# Global settings shared by all workflows
# See: https://docs.chain.link/cre/reference/project-configuration-ts

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: ${SEPOLIA_RPC_URL}

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: ${SEPOLIA_RPC_URL}

# Phase 5: Confidential HTTP (Privacy track) – API keys in enclave
confidential-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: ${SEPOLIA_RPC_URL}

# Tenderly Virtual TestNet - for CRE + Tenderly hackathon track
# Set TENDERLY_VIRTUAL_TESTNET_RPC in your .env file
tenderly-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: ${TENDERLY_VIRTUAL_TESTNET_RPC}
